# Generated by Django 5.2.3 on 2025-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_sensorhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorhistory',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='sensorhistory',
            name='body_temp',
        ),
        migrations.RemoveField(
            model_name='sensorhistory',
            name='location',
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='bp_diastolic',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='bp_systolic',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='temperature',
            field=models.FloatField(default=36.5),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
    ]
