# Generated by Django 5.1.7 on 2025-06-20 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_sensorhistory_blood_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='bp_diastolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='bp_systolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='heart_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensorhistory',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
